Algoritmo "números"

Var
numero: real
dobro: real
terco: real

Inicio
 Escreva("Digite um numero: ")
   Leia (numero)

  dobro<- numero *2
   terco<- numero /1.3

Escreval (" o dobro " , dobro, " o terco " , terco, ".")
Fimalgoritmo




//7) Crie um algoritmo que leia um número real e mostre na tela o seu dobro
// e a sua terça parte. Ex: Digite um número: 3.5 O dobro de 3.5 é 7.0
//A terça parte de 3.5 é 1.16666